version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "parkapp-backend"
    ports:
      - "5001:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "parkapp-frontend"
    ports:
      - "3013:3000"